// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTestCase(arg1) {
  return window['go']['main']['App']['AddTestCase'](arg1);
}

export function ClearTestCases() {
  return window['go']['main']['App']['ClearTestCases']();
}

export function ExecuteStoredTests() {
  return window['go']['main']['App']['ExecuteStoredTests']();
}

export function ExecuteTestsWithId(arg1) {
  return window['go']['main']['App']['ExecuteTestsWithId'](arg1);
}

export function GetTestCases() {
  return window['go']['main']['App']['GetTestCases']();
}
