// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTestCase(arg1) {
  return window['go']['main']['App']['AddTestCase'](arg1);
}

export function ClearTestCases() {
  return window['go']['main']['App']['ClearTestCases']();
}

export function GetTestCases() {
  return window['go']['main']['App']['GetTestCases']();
}

export function MakeRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MakeRequest'](arg1, arg2, arg3, arg4, arg5);
}
