// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTestCase(arg1:main.TestCase):Promise<main.TestCase>;

export function ClearTestCases():Promise<void>;

export function ExecuteStoredTests():Promise<void>;

export function ExecuteTestsWithId(arg1:number):Promise<void>;

export function GetTestCases():Promise<any>;
